-- Do not infer that equal subject values from different issuers identify the
-- same person. OAuth/OIDC identity is the pair (issuer, subject); automatically
-- inserting an alias here could transfer a Blog membership to a different
-- account. Alias creation is handled by the explicit, audited local operation
-- introduced in migration 085 after an operator verifies an authoritative map.
